# 🚨 Security first!
# NEVER put any usernames or passwords in this file at all. We'll handle them securely later.

# List out each of your financial relationships. We'll use these relationships to discover
# each of the underlying accounts. To start things off, we've listed all of the ones that we
# support, so you can just remove or comment out the ones you don't need.
relationships:
  - provider: AdelaideBank
  - provider: AmericanExpress
  - provider: Anz
  - provider: Asgard
  - provider: Bankwest
  - provider: DefenceBank
  - provider: Ing
  - provider: Myki
  - provider: Perpetual
  - provider: TelstraSuper
  - provider: Westpac
