name: Continuous Integration
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    # Caches the contents of the ~/.npm folder on successful build, and attempts to 
    # restores from that cache on each subsequent build
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ubuntu-latest-npm-${{ hashFiles('package-lock.json') }}
        # If cache-miss on exact key, use any previous available caches as the starting point
        restore-keys: |
          ubuntu-latest-npm-
    # `npm ci` uses package-lock.json to restore the exact versions available at commit time
    - run: npm ci
    - run: npm run verify
